port: 8888
log_config:
  version: 1
  formatters:
    standard:
      format: 'PID:%(process)d - %(levelname)s (%(name)s): [%(asctime)s] - %(module)s:%(funcName)s:%(lineno)d: %(message)s'
  handlers:
    default:
      level: 'DEBUG'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
  loggers:
    'overlord.director':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.jail':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.queue':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.client':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands.logs':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.tornado':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands.info':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands.apply':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands.serve':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands.watch':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands.poll':
      handlers: ['default']
      level: 'INFO'
      propagate: false
    'overlord.commands.destroy':
      handlers: ['default']
      level: 'INFO'
      propagate: false
